version: "3.9"

services:
  unity-frontend-app:
    build: .
    container_name: unity-frontend-app
    hostname: unity-frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
